"""add status card fields: progress, operator, duration, distance, airport identity, diverted info

Revision ID: 14d8f07c0a3e
Revises: 93631eb4eb20
Create Date: 2026-09-12 23:44:56.267231

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '14d8f07c0a3e'
down_revision: str | None = '93631eb4eb20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_snapshot', sa.Column('fa_flight_id', sa.String(length=64), nullable=True))
    op.add_column('flight_snapshot', sa.Column('operator_iata', sa.String(length=8), nullable=True))
    op.add_column('flight_snapshot', sa.Column('origin_iata', sa.String(length=4), nullable=True))
    op.add_column('flight_snapshot', sa.Column('origin_name', sa.String(length=200), nullable=True))
    op.add_column('flight_snapshot', sa.Column('origin_city', sa.String(length=100), nullable=True))
    op.add_column('flight_snapshot', sa.Column('origin_timezone', sa.String(length=64), nullable=True))
    op.add_column('flight_snapshot', sa.Column('destination_iata', sa.String(length=4), nullable=True))
    op.add_column('flight_snapshot', sa.Column('destination_name', sa.String(length=200), nullable=True))
    op.add_column('flight_snapshot', sa.Column('destination_city', sa.String(length=100), nullable=True))
    op.add_column('flight_snapshot', sa.Column('destination_timezone', sa.String(length=64), nullable=True))
    op.add_column('flight_snapshot', sa.Column('progress_percent', sa.Integer(), nullable=True))
    op.add_column('flight_snapshot', sa.Column('flight_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('flight_snapshot', sa.Column('route_distance', sa.Integer(), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_destination_code', sa.String(length=8), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_destination_iata', sa.String(length=4), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_destination_name', sa.String(length=200), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_destination_city', sa.String(length=100), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_destination_timezone', sa.String(length=64), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_scheduled_arrival', sa.DateTime(timezone=True), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_estimated_arrival', sa.DateTime(timezone=True), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_actual_arrival', sa.DateTime(timezone=True), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_arrival_gate', sa.String(length=16), nullable=True))
    op.add_column('flight_snapshot', sa.Column('diverted_arrival_terminal', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_snapshot', 'diverted_arrival_terminal')
    op.drop_column('flight_snapshot', 'diverted_arrival_gate')
    op.drop_column('flight_snapshot', 'diverted_actual_arrival')
    op.drop_column('flight_snapshot', 'diverted_estimated_arrival')
    op.drop_column('flight_snapshot', 'diverted_scheduled_arrival')
    op.drop_column('flight_snapshot', 'diverted_destination_timezone')
    op.drop_column('flight_snapshot', 'diverted_destination_city')
    op.drop_column('flight_snapshot', 'diverted_destination_name')
    op.drop_column('flight_snapshot', 'diverted_destination_iata')
    op.drop_column('flight_snapshot', 'diverted_destination_code')
    op.drop_column('flight_snapshot', 'route_distance')
    op.drop_column('flight_snapshot', 'flight_duration_minutes')
    op.drop_column('flight_snapshot', 'progress_percent')
    op.drop_column('flight_snapshot', 'destination_timezone')
    op.drop_column('flight_snapshot', 'destination_city')
    op.drop_column('flight_snapshot', 'destination_name')
    op.drop_column('flight_snapshot', 'destination_iata')
    op.drop_column('flight_snapshot', 'origin_timezone')
    op.drop_column('flight_snapshot', 'origin_city')
    op.drop_column('flight_snapshot', 'origin_name')
    op.drop_column('flight_snapshot', 'origin_iata')
    op.drop_column('flight_snapshot', 'operator_iata')
    op.drop_column('flight_snapshot', 'fa_flight_id')
    # ### end Alembic commands ###
