"""init schema

Revision ID: 737e641b4567
Revises: 
Create Date: 2026-09-12 01:51:21.984038

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '737e641b4567'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_registry',
    sa.Column('icao24', sa.String(length=6), nullable=False),
    sa.Column('registration', sa.String(length=16), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('icao24')
    )
    op.create_index(op.f('ix_aircraft_registry_registration'), 'aircraft_registry', ['registration'], unique=False)
    op.create_table('airport',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=4), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('flight_history_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ident', sa.String(length=16), nullable=False),
    sa.Column('route_origin', sa.String(length=8), nullable=True),
    sa.Column('route_destination', sa.String(length=8), nullable=True),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_history_record_flight_date'), 'flight_history_record', ['flight_date'], unique=False)
    op.create_index(op.f('ix_flight_history_record_ident'), 'flight_history_record', ['ident'], unique=False)
    op.create_table('flight_snapshot',
    sa.Column('flight_id', sa.String(length=64), nullable=False),
    sa.Column('ident', sa.String(length=16), nullable=False),
    sa.Column('operator_icao', sa.String(length=8), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('origin_code', sa.String(length=8), nullable=True),
    sa.Column('destination_code', sa.String(length=8), nullable=True),
    sa.Column('registration', sa.String(length=16), nullable=True),
    sa.Column('aircraft_type', sa.String(length=16), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_gate', sa.String(length=16), nullable=True),
    sa.Column('departure_terminal', sa.String(length=8), nullable=True),
    sa.Column('arrival_gate', sa.String(length=16), nullable=True),
    sa.Column('arrival_terminal', sa.String(length=8), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'LANDED', 'CANCELLED', 'DIVERTED', name='flightstatus'), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_index(op.f('ix_flight_snapshot_ident'), 'flight_snapshot', ['ident'], unique=False)
    op.create_table('live_position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('altitude_ft', sa.Float(), nullable=True),
    sa.Column('ground_speed_kt', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('on_ground', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_snapshot.flight_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_position_flight_id'), 'live_position', ['flight_id'], unique=False)
    op.create_table('tracked_flight',
    sa.Column('flight_id', sa.String(length=64), nullable=False),
    sa.Column('resolved_icao24', sa.String(length=6), nullable=True),
    sa.Column('resolution_method', sa.String(length=32), nullable=True),
    sa.Column('resolution_confidence', sa.String(length=8), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('polling_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_snapshot.flight_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracked_flight')
    op.drop_index(op.f('ix_live_position_flight_id'), table_name='live_position')
    op.drop_table('live_position')
    op.drop_index(op.f('ix_flight_snapshot_ident'), table_name='flight_snapshot')
    op.drop_table('flight_snapshot')
    op.drop_index(op.f('ix_flight_history_record_ident'), table_name='flight_history_record')
    op.drop_index(op.f('ix_flight_history_record_flight_date'), table_name='flight_history_record')
    op.drop_table('flight_history_record')
    op.drop_table('airport')
    op.drop_index(op.f('ix_aircraft_registry_registration'), table_name='aircraft_registry')
    op.drop_table('aircraft_registry')
    # ### end Alembic commands ###
