"""add airport_weather_snapshot table

Revision ID: 87ab6e4fef7c
Revises: 14d8f07c0a3e
Create Date: 2026-09-13 01:53:38.196826

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '87ab6e4fef7c'
down_revision: str | None = '14d8f07c0a3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport_weather_snapshot',
    sa.Column('airport_code', sa.String(length=8), nullable=False),
    sa.Column('current_weather_code', sa.Integer(), nullable=True),
    sa.Column('current_temp_f', sa.Float(), nullable=True),
    sa.Column('current_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hourly_forecast', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['airport_code'], ['airport.code'], ),
    sa.PrimaryKeyConstraint('airport_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airport_weather_snapshot')
    # ### end Alembic commands ###
