"""add operating_ident_icao to flight_snapshot

Revision ID: 93631eb4eb20
Revises: 737e641b4567
Create Date: 2026-09-12 11:49:05.218663

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '93631eb4eb20'
down_revision: str | None = '737e641b4567'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_snapshot', sa.Column('operating_ident_icao', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_snapshot', 'operating_ident_icao')
    # ### end Alembic commands ###
